"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from corsheaders.defaults import default_headers
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


CORS_ALLOW_HEADERS = default_headers + (
    'Access-Control-Allow-Origin',
)

CORS_ALLOW_ALL_ORIGINS=True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#p$%81btc9w+o4xha)c5lr^ka9b%x!01d*kbh0g0t*r5fq5z7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['nlg-backend.herokuapp.com', '127.0.0.1','192.168.168.20','http://192.168.168.20:3000','http://192.168.168.20','http://localhost:3000','http://localhost','http://192.168.168.20:3000','http://192.168.168.20','217.165.8.248','192.168.168.113','192.168.168.52','http://192.168.168.113','http://192.168.168.26','http://192.168.168.113:3000','http://192.168.168.26:3000','http://192.168.168.113:3000','0.0.0.0']
#ALLOWED_HOSTS = ["localhost", "217.165.8.248"]
#ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'store',
    'corsheaders',
    'import_export',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django_user_agents'
]


REST_FRAMEWORK = {

   'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://localhost:3000",
    "http://192.168.168.20:3000",
    "http://192.168.168.20",
    'http://192.168.168.236:3000',
    #"http://192.168.168.20:3000",
    #"http://192.168.168.20:8000",
    'http://192.168.168.113',
    'http://192.168.168.113:3000',
    'http://192.168.168.113:3001',
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'next_level',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'account': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Projectsoverview',
        'USER': 'provus',
        'PASSWORD': 'Pr0@v@2o22',
        'HOST': '192.168.168.111',
        'PORT': '3306',
    },
    'projects': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Accountingbi',
        'USER': 'provus',
        'PASSWORD': 'Pr0@v@2o22',
        'HOST': '192.168.168.111',
        'PORT': '3306',
    },
    'test': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testprogramming',
        'USER': 'read_only_user',
        'PASSWORD': 'ITtest1ng@24',
        'HOST': '192.168.168.111',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_TZ = True


#AUTH_USER_MODEL = "store.CustomUser"
#swappable = 'AUTH_USER_MODEL'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#CORS_ORIGIN_WHITELIST = (
 #   'http//:localhost:3000',
  #  'http://192.168.168.20:3000',
#)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/static/' # 'http://myhost:port/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/' 

DATABASES_ROUTERS = ['routers.db_routers.ProjectRouter']


# Cache backend is optional, but recommended to speed up user agent parsing

# Name of cache backend to cache user agents. If it not specified default
# cache alias will be used. Set to `None` to disable caching.
USER_AGENTS_CACHE = None



EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'nextlevelgroup.do.not.reply@gmail.com'
EMAIL_HOST_PASSWORD = 'kzpqwrqtssarxhtq'
EMAIL_USE_TLS = True