# Generated by Django 4.1.1 on 2022-11-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='0', max_length=100, null=True)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('status_text', models.CharField(default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Finishing',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(default='1', max_length=100, null=True)),
                ('itemcode', models.CharField(max_length=100)),
                ('description', models.TextField(default='NA', null=True)),
                ('length', models.CharField(blank=True, default='NA', max_length=100)),
                ('width', models.CharField(blank=True, default='NA', max_length=100)),
                ('weight', models.CharField(blank=True, default='NA', max_length=100)),
                ('is_length', models.CharField(default='0', max_length=100, null=True)),
                ('is_quantity', models.CharField(default='1', max_length=100, null=True)),
                ('is_both', models.CharField(default='0', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.nameFile)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ItemType',
            },
        ),
        migrations.CreateModel(
            name='MTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=190)),
                ('revision', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=100)),
                ('copy', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('submital', models.CharField(default='0', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MTO',
            },
        ),
        migrations.CreateModel(
            name='MTOImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(default='0', max_length=100, null=True)),
                ('Last', models.CharField(default='0', max_length=100, null=True)),
                ('Gender', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('refrence_no', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('completed_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='NA', max_length=100, null=True)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('status_text', models.CharField(default='Pending', max_length=100, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(null=True)),
                ('TRN', models.CharField(default='1', max_length=100, null=True)),
                ('note', models.CharField(default='NA', max_length=100, null=True)),
                ('orderno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderno', to='store.cartorder')),
                ('projectpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projectpo', to='store.project')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(default='0', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orign', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'System',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Short', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Stock_issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('Issued_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issued_item', to='store.item')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='store.department')),
                ('finishing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Finishing_Issuing', to='store.finishing')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='store.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='store.status')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('length', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Item_Damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_Damage', to='store.item')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_damage', to='store.status')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('forproject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forproject', to='store.project')),
                ('fromproject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromProject', to='store.project')),
                ('item_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_cart', to='store.item')),
                ('mtocart', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtocart', to='store.mto')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('forprojectpo', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forprojectpo', to='store.project')),
                ('fromprojectpo', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromProjectpo', to='store.project')),
                ('mtopo', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtopo', to='store.mto')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_item', to='store.item')),
                ('pono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pono', to='store.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='VI', max_length=30)),
                ('comments', models.CharField(default='Active', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('po_status', models.CharField(default='0', max_length=100, null=True)),
                ('forprojectorder', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forprojectorder', to='store.project')),
                ('fromprojectorder', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromProjectorder', to='store.project')),
                ('mtocartorder', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtocartorder', to='store.mto')),
                ('orderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderNo', to='store.cartorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='MTOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=190)),
                ('extra_quantity', models.CharField(max_length=190)),
                ('revision', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('assigned', models.CharField(default='0', max_length=100, null=True)),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemname', to='store.item')),
                ('mto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mto', to='store.mto')),
            ],
        ),
        migrations.AddField(
            model_name='mto',
            name='projectmto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmto', to='store.project'),
        ),
        migrations.AddField(
            model_name='item',
            name='Supplier',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='store.supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='finishing',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Finishing', to='store.finishing'),
        ),
        migrations.AddField(
            model_name='item',
            name='system',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='System', to='store.system'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='store.itemtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unit', to='store.unit'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='0', max_length=100, null=True)),
                ('stockvalue', models.CharField(default='0', max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='store.item')),
            ],
            options={
                'unique_together': {('item',)},
            },
        ),
    ]
