# Generated by Django 4.1.1 on 2022-11-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Supplier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='store.supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='finishing',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Finishing', to='store.finishing'),
        ),
        migrations.AlterField(
            model_name='item',
            name='system',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='System', to='store.system'),
        ),
    ]
