# Generated by Django 4.1.1 on 2022-11-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_supplier_alter_item_finishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoitem',
            name='cart',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
