# Generated by Django 4.1.1 on 2022-11-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mtoitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowderCoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('copy', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('submital', models.CharField(default='0', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('dnproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dnproject', to='store.project')),
            ],
            options={
                'db_table': 'PowderCoating',
            },
        ),
        migrations.CreateModel(
            name='PowderCoatingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=190)),
                ('revision', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('assigned', models.CharField(default='0', max_length=100, null=True)),
                ('dnitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnitem', to='store.item')),
                ('dno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcno', to='store.powdercoating')),
            ],
        ),
    ]
