# Generated by Django 4.1.1 on 2022-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_powdercoating_powdercoatingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdercoating',
            name='deliveredto',
            field=models.CharField(default='NA', max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='powdercoating',
            name='description',
            field=models.CharField(default='NA', max_length=190, null=True),
        ),
    ]
