# Generated by Django 4.1.1 on 2022-12-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_stock_issuing_issuingmto_alter_powdercoating_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='color',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductionIssuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('color', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Issued_item_reserved', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Issued_item_reserved', to='store.stock_issuing')),
                ('Issuingproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IssuingProject', to='store.project')),
                ('Production_Issued_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Production_Issued_item', to='store.item')),
                ('issuedmto', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuedmto', to='store.mto')),
            ],
        ),
    ]
