# Generated by Django 4.1.1 on 2022-12-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_stock_issuing_color_productionissuing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
