# Generated by Django 4.1.1 on 2022-12-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_powdercoatingitems_issued_item_pc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdercoatingitems',
            name='remark',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
