# Generated by Django 4.1.1 on 2022-12-12 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_powdercoatingitems_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtoitem',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
