# Generated by Django 4.1.1 on 2022-12-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_mtoitem_created_at_mtoitem_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdercoating',
            name='note',
            field=models.CharField(default='NA', max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='powdercoating',
            name='status',
            field=models.CharField(default='NA', max_length=190, null=True),
        ),
    ]
