# Generated by Django 4.1.1 on 2022-12-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_powdercoating_note_alter_powdercoating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powdercoating',
            name='status',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
