# Generated by Django 4.1.1 on 2022-12-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_powdercoating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powdercoating',
            name='copy',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
