# Generated by Django 4.1.1 on 2022-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_powdercoating_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powdercoatingitems',
            name='revision',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
