# Generated by Django 4.1.1 on 2022-12-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_powdercoatingitems_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='CORVISION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Corvision',
            },
        ),
        migrations.CreateModel(
            name='CorVisionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='COR', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('fromula', models.CharField(max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVision', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionItem', to='store.item')),
            ],
        ),
    ]
