# Generated by Django 4.1.1 on 2022-12-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_corvision_corvisionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvisionprofile',
            name='coating',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='corvisionprofile',
            name='cutting',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='corvisionprofile',
            name='remark',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
