# Generated by Django 4.1.1 on 2022-12-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_corvisionprofile_coating_corvisionprofile_cutting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvision',
            name='wd',
            field=models.CharField(default='2', max_length=100),
        ),
    ]
