# Generated by Django 4.1.1 on 2022-12-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_corvision_wd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corvision',
            old_name='name',
            new_name='Windowname',
        ),
        migrations.AlterModelTable(
            name='corvision',
            table=None,
        ),
    ]
