# Generated by Django 4.1.1 on 2022-12-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_name_corvision_windowname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corvision',
            old_name='Windowname',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='corvision',
            table='Corvision',
        ),
    ]
