# Generated by Django 4.1.1 on 2022-12-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_corvision_name_alter_corvision_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVisionShutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='COR', max_length=100)),
                ('fromula', models.CharField(max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionShutter', to='store.corvision')),
            ],
        ),
        migrations.CreateModel(
            name='CorVisionGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='COR', max_length=100)),
                ('fromula', models.CharField(max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionGlass', to='store.corvision')),
            ],
        ),
        migrations.CreateModel(
            name='CorVisionDIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='COR', max_length=100)),
                ('fromula', models.CharField(max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionDIM', to='store.corvision')),
            ],
        ),
    ]
