# Generated by Django 4.1.1 on 2022-12-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_corvisionshutter_corvisionglass_corvisiondim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corvisiondim',
            old_name='fromula',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='corvisionglass',
            old_name='fromula',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='corvisionshutter',
            old_name='fromula',
            new_name='formula',
        ),
    ]
