# Generated by Django 4.1.1 on 2022-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_fromula_corvisiondim_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corvisionglass',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='corvisionshutter',
            name='formula',
        ),
        migrations.AddField(
            model_name='corvisionglass',
            name='Heightformula',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='corvisionglass',
            name='Widthformula',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='corvisionshutter',
            name='Heightformula',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='corvisionshutter',
            name='Widthformula',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
