# Generated by Django 4.1.1 on 2022-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_corvisionglass_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvisiondim',
            name='CodeName',
            field=models.CharField(default='dim', max_length=100),
        ),
    ]
