# Generated by Django 4.1.1 on 2022-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_corvisiondim_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvisionglass',
            name='CodeName',
            field=models.CharField(default='gls', max_length=100),
        ),
        migrations.AddField(
            model_name='corvisionshutter',
            name='CodeName',
            field=models.CharField(default='sht', max_length=100),
        ),
    ]
