# Generated by Django 4.1.1 on 2022-12-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_corvisionglass_codename_corvisionshutter_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVisionHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hardware', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionHardware', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionHardItem', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='CorVisionGasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gasket', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionGas', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionGasItem', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='CorVisionAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Acc', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionAcc', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionAccItem', to='store.item')),
            ],
        ),
    ]
