# Generated by Django 4.1.1 on 2022-12-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_corvisionacc_coating_corvisionacc_cutting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVisionGasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gasket', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('fromula', models.CharField(max_length=200, null='1')),
                ('cutting', models.CharField(default='NA', max_length=200)),
                ('coating', models.CharField(default='NA', max_length=200)),
                ('remark', models.CharField(default='NA', max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionGasket', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionGasketItem', to='store.item')),
            ],
        ),
    ]
