# Generated by Django 4.1.1 on 2022-12-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_corvisiongasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='refrence',
            field=models.CharField(default='PO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
