# Generated by Django 4.1.1 on 2022-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_purchaseorder_refrence_alter_project_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='balance',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
