# Generated by Django 4.1.1 on 2022-12-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_item_weight_alter_purchaseorder_orderno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='pono',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pono', to='store.purchaseorder'),
        ),
    ]
