# Generated by Django 4.1.1 on 2023-01-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_purchaseorderitems_pono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=100)),
                ('copy', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('submital', models.CharField(default='0', max_length=100, null=True)),
                ('description', models.CharField(default='NA', max_length=190, null=True)),
                ('deliveredto', models.CharField(default='NA', max_length=190, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('note', models.CharField(default='NA', max_length=190, null=True)),
                ('sproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sproject', to='store.project')),
            ],
            options={
                'db_table': 'Stripping',
            },
        ),
        migrations.CreateModel(
            name='StrippingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=190)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('remark', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('assigned', models.CharField(default='1', max_length=100, null=True)),
                ('sitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stitem', to='store.item')),
                ('stno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stno', to='store.stripping')),
            ],
        ),
    ]
