# Generated by Django 4.1.1 on 2023-01-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_stripping_strippingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample',
            field=models.BooleanField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='strippingitems',
            name='remark',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
