# Generated by Django 4.1.1 on 2023-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_project_sample_alter_strippingitems_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
