# Generated by Django 4.1.1 on 2023-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_project_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='description',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
