# Generated by Django 4.1.1 on 2023-01-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_stock_issuing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoitem',
            name='remarks',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
