# Generated by Django 4.1.1 on 2023-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_mtoitem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='strippingitems',
            name='wastage',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
