# Generated by Django 4.1.1 on 2023-01-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_stock_issuing_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdetail',
            name='Supplier',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderSupplier', to='store.supplier'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='Supplier',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartSupplier', to='store.supplier'),
        ),
    ]
