# Generated by Django 4.1.1 on 2023-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_orderitemdetail_supplier_shopping_cart_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='priority',
            field=models.CharField(default='Normal', max_length=100, null=True),
        ),
    ]
