# Generated by Django 4.1.1 on 2023-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_cartorder_created_at_alter_cartorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alternate',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
