# Generated by Django 4.1.1 on 2023-01-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_stockalternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pitem', to='store.item')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='store.item')),
            ],
        ),
    ]
