# Generated by Django 4.1.1 on 2023-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_productionstock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdercoatingitems',
            name='custom',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='powdercoatingitems',
            name='length',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
