# Generated by Django 4.1.1 on 2023-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_powdercoatingitems_custom_powdercoatingitems_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powdercoatingitems',
            name='length',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
