# Generated by Django 4.1.1 on 2023-01-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_powdercoatingitems_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='PurchaseSupplier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseSupplier', to='store.supplier'),
        ),
    ]
