# Generated by Django 4.1.1 on 2023-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_purchaseorder_purchasesupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='previous_price',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
