# Generated by Django 4.1.1 on 2023-01-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_item_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='price',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
