# Generated by Django 4.1.1 on 2023-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_purchaseorderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
