# Generated by Django 4.1.1 on 2023-01-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_stock_issuing_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_issuing',
            name='update',
        ),
    ]
