# Generated by Django 4.1.1 on 2023-01-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_remove_stock_issuing_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteFromSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('DNFromsupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DNFromsupplier', to='store.supplier')),
                ('DNFromsupplierProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierProject', to='store.project')),
            ],
        ),
    ]
