# Generated by Django 4.1.1 on 2023-01-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_deliverynotefromsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryNoteFromSupplier',
        ),
    ]
