# Generated by Django 4.1.1 on 2023-01-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_delete_deliverynotefromsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtoitem',
            name='update',
        ),
    ]
