# Generated by Django 4.1.1 on 2023-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_remove_mtoitem_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteFromSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
