# Generated by Django 4.1.1 on 2023-01-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_deliverynotefromsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynotefromsupplier',
            name='DNFromsupplierName',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='DNFromsupplierName', to='store.supplier'),
        ),
    ]
