# Generated by Django 4.1.1 on 2023-01-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_deliverynotefromsupplier_dnfromsuppliername'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='actual_quantity',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
