# Generated by Django 4.1.1 on 2023-01-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_purchaseorderitems_vat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='description',
            new_name='payment_term',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='TRN',
        ),
    ]
