# Generated by Django 4.1.1 on 2023-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_rename_description_purchaseorder_payment_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
