# Generated by Django 4.1.1 on 2023-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_purchaseorder_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionissuing',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productionissuing',
            name='update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
