# Generated by Django 4.1.1 on 2023-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_productionissuing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstock',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
