# Generated by Django 4.1.1 on 2023-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_productionstock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='powdercoatingitems',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='powdercoatingitems',
            name='update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
