# Generated by Django 4.1.1 on 2023-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_powdercoatingitems_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionissuing',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
