# Generated by Django 4.1.1 on 2023-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_alter_productionissuing_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionissuing',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
