# Generated by Django 4.1.1 on 2023-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_remove_productionissuing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='local',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
