# Generated by Django 4.1.1 on 2023-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_purchaseorder_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='PerformaInvoice',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
