# Generated by Django 4.1.1 on 2023-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_purchaseorder_accounts_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='accounts_submital',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
