# Generated by Django 4.1.1 on 2023-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_purchaseorder_accounts_submital'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
