# Generated by Django 4.1.1 on 2023-02-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_purchaseorder_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='updated_at',
        ),
    ]
