# Generated by Django 4.1.1 on 2023-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_remove_purchaseorder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='remarks',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
