# Generated by Django 4.1.1 on 2023-02-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_purchaseorderitems_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='remarks',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
