# Generated by Django 4.1.1 on 2023-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_alter_purchaseorderitems_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pi_approval',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
