# Generated by Django 4.1.1 on 2023-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_purchaseorder_pi_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='revoke',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
