# Generated by Django 4.1.1 on 2023-02-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_stock_issuing_revoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryNoteFromSupplier',
        ),
    ]
