# Generated by Django 4.1.1 on 2023-02-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_delete_deliverynotefromsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteFromSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('DNFromsupplierName', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='DNFromsupplierName', to='store.supplier')),
            ],
        ),
    ]
