# Generated by Django 4.1.1 on 2023-02-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_deliverynotefromsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynotefromsupplier',
            name='DNINPurchaseOrder',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DNINPurchaseOrder', to='store.purchaseorder'),
        ),
    ]
