# Generated by Django 4.1.1 on 2023-02-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_deliverynotefromsupplier_dninpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='POItemorderno',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POItemorderno', to='store.cartorder'),
        ),
    ]
