# Generated by Django 4.1.1 on 2023-02-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_purchaseorderitems_pouom'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteFromSupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('DNINFromsupplierNo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='DNINFromsupplierNo', to='store.deliverynotefromsupplier')),
                ('orderitemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemid', to='store.purchaseorderitems')),
                ('recievedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievedItem', to='store.item')),
            ],
        ),
    ]
