# Generated by Django 4.1.1 on 2023-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_purchaseorder_quotationrefrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='discount',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
