# Generated by Django 4.1.1 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_alter_purchaseorderitems_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='basket',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
