# Generated by Django 4.1.1 on 2023-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0099_shopping_cart_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
