# Generated by Django 4.1.1 on 2023-02-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0100_alter_item_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
