# Generated by Django 4.1.1 on 2023-02-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_alter_purchaseorderitems_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190, null=True)),
            ],
            options={
                'db_table': 'AccountsHead',
            },
        ),
    ]
