# Generated by Django 4.1.1 on 2023-02-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_accountshead'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitems',
            name='accountshead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountshead', to='store.accountshead'),
        ),
    ]
