# Generated by Django 4.1.1 on 2023-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_purchaseorderitems_accountshead'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountshead',
            name='code',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
