# Generated by Django 4.1.1 on 2023-02-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_accountshead_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='accountshead',
            field=models.ForeignKey(blank=True, default='78', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountshead', to='store.accountshead'),
        ),
    ]
