# Generated by Django 4.1.1 on 2023-02-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0107_cartorder_refrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='refrence',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='quotaionproject',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotaionproject', to='store.project'),
        ),
    ]
