# Generated by Django 4.1.1 on 2023-02-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0108_remove_cartorder_refrence_cartorder_quotaionproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('amount', models.CharField(default='1', max_length=100, null=True)),
                ('vat', models.CharField(default='1', max_length=100, null=True)),
                ('Quotationdno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quotationdno', to='store.powdercoating')),
                ('QuotationorderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuotationorderNo', to='store.cartorder')),
                ('projectorderquotation', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectorderquotation', to='store.project')),
                ('quotationuom', models.ForeignKey(blank=True, default='16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotationuom', to='store.unit')),
            ],
        ),
    ]
