# Generated by Django 4.1.1 on 2023-02-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0110_alter_orderitemquotation_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemquotation',
            name='vat',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
