# Generated by Django 4.1.1 on 2023-02-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_alter_orderitemquotation_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default='0', max_length=100, null=True),
        ),
    ]
