# Generated by Django 4.1.1 on 2023-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='quotaionproject',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='quotation',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
