# Generated by Django 4.1.1 on 2023-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0117_orderitemquotation_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemquotation',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
