# Generated by Django 4.1.1 on 2023-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0118_orderitemquotation_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemquotation',
            name='weight',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
