# Generated by Django 4.1.1 on 2023-02-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0119_alter_orderitemquotation_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderQuotationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_item_title', models.CharField(max_length=100, null=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('price', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('balance', models.CharField(default='0', max_length=100)),
                ('weight', models.CharField(default='0', max_length=100)),
                ('vat', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('POQItemorderno', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POQItemorderno', to='store.orderitemquotation')),
                ('po_item_project', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_item_project', to='store.project')),
                ('qpouom', models.ForeignKey(blank=True, default='16', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qpouom', to='store.unit')),
                ('quot_item_pono', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quot_item_pono', to='store.purchaseorder')),
                ('quotaccountshead', models.ForeignKey(blank=True, default='78', on_delete=django.db.models.deletion.CASCADE, related_name='quotaccountshead', to='store.accountshead')),
                ('quotitemdn', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotitemdn', to='store.powdercoating')),
            ],
        ),
    ]
