# Generated by Django 4.1.1 on 2023-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0120_purchaseorderquotationitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='serviceQuotation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
