# Generated by Django 4.1.1 on 2023-02-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0123_alter_supplier_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='description',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
