# Generated by Django 4.1.1 on 2023-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0124_alter_cartorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='returned',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
