# Generated by Django 4.1.1 on 2023-02-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0127_sitedeliverynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDeliveryNoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('SiteItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteItem', to='store.item')),
                ('site_delivery_note_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_delivery_note_no', to='store.sitedeliverynote')),
                ('sitedeliverymto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitedeliverymto', to='store.project')),
            ],
        ),
    ]
