# Generated by Django 4.1.1 on 2023-02-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0128_sitedeliverynoteitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedeliverynoteitems',
            name='site_issuing_id',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_issuing_id', to='store.stock_issuing'),
        ),
        migrations.AlterField(
            model_name='sitedeliverynoteitems',
            name='sitedeliverymto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitedeliverymto', to='store.mto'),
        ),
    ]
