# Generated by Django 4.1.1 on 2023-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0129_sitedeliverynoteitems_site_issuing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedeliverynoteitems',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
