# Generated by Django 4.1.1 on 2023-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0130_sitedeliverynoteitems_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedeliverynoteitems',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
