# Generated by Django 4.1.1 on 2023-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0131_alter_sitedeliverynoteitems_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedeliverynoteitems',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
