# Generated by Django 4.1.1 on 2023-03-02 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0132_alter_sitedeliverynoteitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mto',
            name='submitted_at',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
