# Generated by Django 4.1.1 on 2023-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0133_mto_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='forproject',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forproject', to='store.project'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='fromproject',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromProject', to='store.project'),
        ),
    ]
