# Generated by Django 4.1.1 on 2023-03-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0134_alter_shopping_cart_forproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pi_submital',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
