# Generated by Django 4.1.1 on 2023-03-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0135_purchaseorder_pi_submital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='pi_submital',
        ),
    ]
