# Generated by Django 4.1.1 on 2023-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0136_remove_purchaseorder_pi_submital'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='total',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
