# Generated by Django 4.1.1 on 2023-03-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0138_corvisionacc_formula_alter_corvisionprofile_cutting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorScrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gasket', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('fromula', models.CharField(max_length=200, null='1')),
                ('cutting', models.CharField(default='NA', max_length=200)),
                ('coating', models.CharField(default='NA', max_length=200)),
                ('remark', models.CharField(default='NA', max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionScrew', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionScrewItem', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='CorPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gasket', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('fromula', models.CharField(max_length=200, null='1')),
                ('cutting', models.CharField(default='NA', max_length=200)),
                ('coating', models.CharField(default='NA', max_length=200)),
                ('remark', models.CharField(default='NA', max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionPacking', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionPackingItem', to='store.item')),
            ],
        ),
    ]
