# Generated by Django 4.1.1 on 2023-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0139_corscrew_corpacking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpacking',
            old_name='fromula',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='corscrew',
            old_name='fromula',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='corvisiongasket',
            old_name='fromula',
            new_name='formula',
        ),
    ]
