# Generated by Django 4.1.1 on 2023-03-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0140_rename_fromula_corpacking_formula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corvisionprofile',
            old_name='fromula',
            new_name='formula',
        ),
    ]
