# Generated by Django 4.1.1 on 2023-03-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0141_rename_fromula_corvisionprofile_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpacking',
            name='title',
            field=models.CharField(default='Packing', max_length=100),
        ),
        migrations.AlterField(
            model_name='corscrew',
            name='title',
            field=models.CharField(default='Screw', max_length=100),
        ),
    ]
