# Generated by Django 4.1.1 on 2023-03-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0143_alter_purchaseorder_quotationrefrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVisionInterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gasket', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('formula', models.CharField(max_length=200, null='1')),
                ('maximum', models.CharField(max_length=200, null='0')),
                ('cutting', models.CharField(default='NA', max_length=200)),
                ('coating', models.CharField(default='NA', max_length=200)),
                ('remark', models.CharField(default='NA', max_length=200)),
                ('CorVision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionInterLock', to='store.corvision')),
                ('CorVisionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorVisionInterLockItem', to='store.item')),
            ],
        ),
    ]
