# Generated by Django 4.1.1 on 2023-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0144_corvisioninterlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvisioninterlock',
            name='minimum',
            field=models.CharField(max_length=200, null='0'),
            preserve_default='0',
        ),
    ]
