# Generated by Django 4.1.1 on 2023-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0146_corvisioninterlock_heightformula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corvisioninterlock',
            name='heightFormula',
        ),
        migrations.AddField(
            model_name='corvisiondim',
            name='heightFormula',
            field=models.CharField(max_length=200, null='1'),
            preserve_default='1',
        ),
    ]
