# Generated by Django 4.1.1 on 2023-04-06 06:01

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0151_corvisioninterlock_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvision',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.nameFile),
        ),
    ]
