# Generated by Django 4.1.1 on 2023-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0155_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('windload', models.CharField(max_length=100)),
            ],
        ),
    ]
