# Generated by Django 4.1.1 on 2023-04-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0156_releasedwindow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleasedWindow',
        ),
    ]
