# Generated by Django 4.1.1 on 2023-04-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0157_delete_releasedwindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('GlassColor', models.CharField(default='AG', max_length=100)),
                ('ProfileFinishing', models.CharField(default='AC', max_length=100)),
                ('LockHeight', models.CharField(default='1050', max_length=100)),
                ('LockFinishing', models.CharField(default='AC', max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('elevation', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('windload', models.CharField(max_length=100)),
                ('Window', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Window', to='store.corvision')),
                ('WindowLock', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='WindowLock', to='store.lock')),
                ('Windowproject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Windowproject', to='store.project')),
            ],
        ),
    ]
