# Generated by Django 4.1.1 on 2023-04-25 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0158_releasedwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedwindow',
            name='Windowfloor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Floor', to='store.floor'),
        ),
    ]
