# Generated by Django 4.1.1 on 2023-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0160_releasedwindowprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedwindowprofile',
            name='ProfileUOM',
        ),
    ]
