# Generated by Django 4.1.1 on 2023-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0161_remove_releasedwindowprofile_profileuom'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
