# Generated by Django 4.1.1 on 2023-04-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0162_windowstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedwindow',
            name='status',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='store.windowstatus'),
        ),
    ]
