# Generated by Django 4.1.1 on 2023-04-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0164_alter_releasedwindow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedwindow',
            name='status',
        ),
    ]
