# Generated by Django 4.1.1 on 2023-04-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0166_releasedwindow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedwindow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='store.windowstatus'),
        ),
    ]
