# Generated by Django 4.1.1 on 2023-04-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0168_alter_releasedwindow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedwindowprofile',
            name='ReleasedWindowP',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowP', to='store.releasedwindow'),
        ),
        migrations.AlterField(
            model_name='releasedwindowprofile',
            name='ReleasedWindowPItem',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowPItem', to='store.item'),
        ),
    ]
