# Generated by Django 4.1.1 on 2023-04-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0169_releasedwindowprofile_releasedwindowp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedWindowScrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowS', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowS', to='store.releasedwindow')),
                ('ReleasedWindowSc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowSc', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedWindowPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowPac', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowPac', to='store.item')),
                ('ReleasedWindowPacking', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowPacking', to='store.releasedwindow')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedWindowGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('ReleasedWindowGlass', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowGlass', to='store.releasedwindow')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedWindowGasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowG', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowG', to='store.releasedwindow')),
                ('ReleasedWindowGasket', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowGasket', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedWindowACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowA', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowA', to='store.releasedwindow')),
                ('ReleasedWindowAcc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowAcc', to='store.item')),
            ],
        ),
    ]
