# Generated by Django 4.1.1 on 2023-04-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0170_releasedwindowscrew_releasedwindowpacking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedWindowInterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowInter', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowInter', to='store.releasedwindow')),
                ('ReleasedWindowInterProfile', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowInterProfile', to='store.item')),
            ],
        ),
    ]
