# Generated by Django 4.1.1 on 2023-04-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0171_releasedwindowinterlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedWindowInterLockACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('ReleasedWindowInterA', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowInterA', to='store.releasedwindow')),
                ('ReleasedWindowInterAcc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedWindowInterAcc', to='store.item')),
            ],
        ),
    ]
