# Generated by Django 4.1.1 on 2023-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0172_releasedwindowinterlockacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdetail',
            name='hidden',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
