# Generated by Django 4.1.1 on 2023-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0173_orderitemdetail_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemquotation',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
