# Generated by Django 4.1.1 on 2023-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0175_alter_purchaseorderquotationitems_po_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_issuing',
            name='restore',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
