# Generated by Django 4.1.1 on 2023-06-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0176_stock_issuing_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedwindowprofile',
            name='Releasedprofileproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Releasedprofileproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowprofile',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
