# Generated by Django 4.1.1 on 2023-06-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0177_releasedwindowprofile_releasedprofileproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedwindowacc',
            name='ReleasedAccproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedAccproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowacc',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowgasket',
            name='ReleasedGasketroject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedGasketroject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowgasket',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowglass',
            name='ReleasedGlassproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedGlassproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowglass',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowinterlock',
            name='ReleasedInterLockproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedInterLockproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowinterlock',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowinterlockacc',
            name='ReleasedInterLockAccproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedInterLockAccproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowinterlockacc',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowpacking',
            name='ReleasedPackingproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedPackingproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowpacking',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='releasedwindowscrew',
            name='ReleasedScrewproject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ReleasedScrewproject', to='store.project'),
        ),
        migrations.AddField(
            model_name='releasedwindowscrew',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
