# Generated by Django 4.1.1 on 2023-06-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0178_releasedwindowacc_releasedaccproject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasedwindowprofile',
            options={'ordering': ['cutlength']},
        ),
    ]
