# Generated by Django 4.1.1 on 2023-06-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0179_alter_releasedwindowprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasedwindowprofile',
            options={'ordering': ['-cutlength']},
        ),
    ]
