# Generated by Django 4.1.1 on 2023-06-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0180_alter_releasedwindowprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasedwindowprofile',
            options={},
        ),
    ]
