# Generated by Django 4.1.1 on 2023-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0181_alter_releasedwindowprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedwindowprofile',
            name='cutlength',
            field=models.FloatField(max_length=100),
        ),
    ]
