# Generated by Django 4.1.1 on 2023-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0184_mto_mtotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtotype',
            name='title',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
