# Generated by Django 4.1.1 on 2023-06-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0185_alter_mtotype_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mto',
            name='MTOType',
        ),
    ]
