# Generated by Django 4.1.1 on 2023-06-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0186_remove_mto_mtotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mto',
            name='MTOType',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='mtotype', to='store.mtotype'),
        ),
    ]
