# Generated by Django 4.1.1 on 2023-06-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0187_mto_mtotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('ProjectStockList', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ProjectStockList', to='store.project')),
                ('Type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='store.mtotype')),
            ],
        ),
        migrations.CreateModel(
            name='StockListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('StockListItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockListItem', to='store.stocklist')),
            ],
        ),
    ]
