# Generated by Django 4.1.1 on 2023-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0188_stocklist_stocklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
