# Generated by Django 4.1.1 on 2023-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0189_stocklist_status_stocklist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklistitem',
            name='StockListID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='StockListID', to='store.stocklist'),
        ),
        migrations.AlterField(
            model_name='stocklistitem',
            name='StockListItem',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='StockListItem', to='store.item'),
        ),
    ]
