# Generated by Django 4.1.1 on 2023-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0192_projectslist_projectsmanagers_projoverview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vodetails',
            fields=[
                ('void', models.SmallAutoField(db_column='VOID', primary_key=True, serialize=False)),
                ('projectid', models.SmallIntegerField(db_column='ProjectID')),
                ('vonb', models.CharField(db_column='VONB', max_length=3)),
                ('voamount', models.FloatField(db_column='VOamount')),
                ('vodate', models.DateField(db_column='VOdate')),
                ('vodescription', models.CharField(blank=True, db_column='VODescription', max_length=45, null=True)),
                ('voapprovalstatus', models.CharField(db_column='VOApprovalStatus', max_length=20)),
                ('voapprovalform', models.CharField(blank=True, db_column='VOapprovalForm', max_length=20, null=True)),
                ('voapprovaldate', models.DateField(db_column='VOapprovalDate')),
            ],
            options={
                'db_table': 'vodetails',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='externaluserID',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='balance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
