# Generated by Django 4.1.1 on 2023-10-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0193_vodetails_profile_externaluserid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certifiedpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eventslogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('GlassColor', models.CharField(default='AG', max_length=100)),
                ('ProfileFinishing', models.CharField(default='AC', max_length=100)),
                ('LockHeight', models.CharField(default='1050', max_length=100)),
                ('LockFinishing', models.CharField(default='AC', max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('elevation', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('windload', models.CharField(max_length=100)),
                ('FWindow', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FWindow', to='store.corvision')),
                ('FWindowLock', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FWindowLock', to='store.lock')),
                ('FWindowfloor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FFloor', to='store.floor')),
                ('FWindowproject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FWindowproject', to='store.project')),
                ('Fstatus', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Fstatus', to='store.windowstatus')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedAccproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedAccproject', to='store.project')),
                ('FReleasedWindowA', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowA', to='store.releasedwindow')),
                ('FReleasedWindowAcc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowAcc', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowGasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedGasketroject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedGasketroject', to='store.project')),
                ('FReleasedWindowG', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowG', to='store.releasedwindow')),
                ('FReleasedWindowGasket', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowGasket', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedGlassproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedGlassproject', to='store.project')),
                ('FReleasedWindowGlass', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowGlass', to='store.releasedwindow')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowInterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedInterLockproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedInterLockproject', to='store.project')),
                ('FReleasedWindowInter', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowInter', to='store.releasedwindow')),
                ('FReleasedWindowInterProfile', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowInterProfile', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowInterLockACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedInterLockAccproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedInterLockAccproject', to='store.project')),
                ('FReleasedWindowInterA', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowInterA', to='store.releasedwindow')),
                ('FReleasedWindowInterAcc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowInterAcc', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedPackingproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedPackingproject', to='store.project')),
                ('FReleasedWindowPac', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowPac', to='store.item')),
                ('FReleasedWindowPacking', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowPacking', to='store.releasedwindow')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('cutlength', models.FloatField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('cutting', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedWindowP', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowP', to='store.releasedwindow')),
                ('FReleasedWindowPItem', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowPItem', to='store.item')),
                ('FReleasedprofileproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedprofileproject', to='store.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReleasedWindowScrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('coating', models.CharField(default='NA', max_length=100)),
                ('remark', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('FReleasedScrewproject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedScrewproject', to='store.project')),
                ('FReleasedWindowS', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowS', to='store.releasedwindow')),
                ('FReleasedWindowSc', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FReleasedWindowSc', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='Finishingtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Glasstypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters4Po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paymentterms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paymenttypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projectpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='projectsoverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Projoverview',
        ),
        migrations.AlterModelOptions(
            name='projectslist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsmanagers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vodetails',
            options={},
        ),
    ]
