# Generated by Django 4.1.1 on 2023-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0195_remove_projectslist_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corvision',
            name='subsystem',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='corvision',
            name='system',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
