# Generated by Django 4.1.1 on 2023-10-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0199_releasedcustomdim_finalreleasedcustomdim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedcustomdim',
            name='dim1',
        ),
        migrations.RemoveField(
            model_name='releasedcustomdim',
            name='dim2',
        ),
        migrations.RemoveField(
            model_name='releasedcustomdim',
            name='dim3',
        ),
    ]
