# Generated by Django 4.1.1 on 2023-12-14 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0202_stock_issuing_revremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='1', max_length=100)),
                ('revision', models.CharField(default='1', max_length=100)),
                ('submitted_at', models.DateField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(max_length=200)),
                ('TentaiveGlassProject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='TentaiveGlassProject', to='store.project')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TentativeGlass',
            },
        ),
        migrations.CreateModel(
            name='TentativeGlassProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=100)),
            ],
            options={
                'db_table': 'TentativeGlassProcessor',
            },
        ),
        migrations.CreateModel(
            name='TentativeGlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NA', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='1', max_length=100)),
            ],
            options={
                'db_table': 'TentativeGlassType',
            },
        ),
        migrations.CreateModel(
            name='TentativeGlassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WindowRef', models.CharField(default='1', max_length=100)),
                ('window', models.CharField(default='1', max_length=100)),
                ('height', models.CharField(default='1', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('area', models.CharField(default='1', max_length=100)),
                ('system', models.CharField(default='1', max_length=100)),
                ('location', models.CharField(default='1', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('TentaiveGlassType', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='TentaiveGlassType', to='store.tentativeglasstype')),
                ('TentativeGlassID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='TentativeGlassID', to='store.tentativeglass')),
            ],
            options={
                'db_table': 'TentativeGlassItem',
            },
        ),
        migrations.CreateModel(
            name='TentativeGlassFinalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WindowRef', models.CharField(default='1', max_length=100)),
                ('window', models.CharField(default='1', max_length=100)),
                ('height', models.CharField(default='1', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('area', models.CharField(default='1', max_length=100)),
                ('system', models.CharField(default='1', max_length=100)),
                ('location', models.CharField(default='1', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('FinalTentaiveGlassType', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FinalTentaiveGlassType', to='store.tentativeglasstype')),
                ('FinalTentativeGlassID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='FinalTentativeGlassID', to='store.tentativeglass')),
            ],
            options={
                'db_table': 'TentativeGlassFinalItem',
            },
        ),
        migrations.CreateModel(
            name='TentativeGlassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_date', models.DateField(auto_now_add=True, null=True)),
                ('quotation_receiving_date', models.DateField(auto_now_add=True, null=True)),
                ('booking_cofirmation_date', models.DateField(auto_now_add=True, null=True)),
                ('QuotationRef', models.CharField(default='1', max_length=100)),
                ('GlassType', models.CharField(default='1', max_length=100)),
                ('area', models.CharField(default='1', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('remarks', models.CharField(default='1', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('GlassProcessor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='GlassProcessor', to='store.tentativeglassprocessor')),
                ('TentaiveGlassBookingProject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='TentaiveGlassBookingProject', to='store.project')),
                ('purchaseRef', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseRef', to='store.purchaseorder')),
            ],
            options={
                'db_table': 'TentativeGlassBooking',
            },
        ),
    ]
