# Generated by Django 4.1.1 on 2023-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0203_tentativeglass_tentativeglassprocessor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='certifiedpayment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eventslogging',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='finishingtype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='glasstypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoicing',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parameters4po',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paymenttypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectpayments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectslist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectsmanagers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='projectsoverview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vodetails',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='tentativeglassfinalitem',
            old_name='window',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='tentativeglass',
            name='submitted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tentativeglassbooking',
            name='booking_cofirmation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tentativeglassbooking',
            name='inquiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tentativeglassbooking',
            name='quotation_receiving_date',
            field=models.DateField(null=True),
        ),
    ]
