# Generated by Django 4.1.1 on 2023-12-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0204_alter_attachments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='certifiedpayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventslogging',
            options={},
        ),
        migrations.AlterModelOptions(
            name='finishingtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='glasstypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoicing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parameters4po',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentterms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymenttypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectpayments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectslist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsmanagers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsoverview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vodetails',
            options={},
        ),
    ]
