# Generated by Django 4.1.1 on 2023-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0206_tentativeglassbooking_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeglassbooking',
            name='purchaseRef',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
