# Generated by Django 4.1.1 on 2023-12-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0207_alter_tentativeglassbooking_purchaseref'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TentativeGlassFinalItem',
        ),
    ]
