# Generated by Django 4.1.1 on 2023-12-21 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0208_delete_tentativeglassfinalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassCutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='1', max_length=100)),
                ('revision', models.CharField(default='1', max_length=100)),
                ('submitted_at', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=200)),
                ('TentaiveGlassCuttingProject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='TentaiveGlassCuttingProject', to='store.project')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GlassCutting',
            },
        ),
    ]
