# Generated by Django 4.1.1 on 2023-12-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0210_tentativeglassfinalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glasscutting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='glasscutting',
            name='submitted_at',
        ),
    ]
