# Generated by Django 4.1.1 on 2023-12-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0211_remove_glasscutting_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glasscutting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glasscutting',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='glasscutting',
            name='status',
        ),
    ]
