# Generated by Django 4.1.1 on 2023-12-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0213_glasscutting_created_at_glasscutting_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='glass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tentativeglassfinalitem',
            name='po',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.CreateModel(
            name='PurchaseOrderGlassItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('price', models.CharField(default='0', max_length=100, null=True)),
                ('description', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.IntegerField(default='1')),
                ('balance', models.IntegerField(default='0')),
                ('area', models.IntegerField(default='0')),
                ('vat', models.CharField(default='0', max_length=100)),
                ('uchannels', models.CharField(default='0', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('discount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('POGlassType', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='POGlassType', to='store.tentativeglasstype')),
                ('gaccountshead', models.ForeignKey(blank=True, default='78', on_delete=django.db.models.deletion.CASCADE, related_name='gaccountshead', to='store.accountshead')),
                ('glasscutting', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glasscutting', to='store.glasscutting')),
                ('gpono', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpono', to='store.purchaseorder')),
            ],
        ),
    ]
