# Generated by Django 4.1.1 on 2023-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0214_purchaseorder_glass_tentativeglassfinalitem_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='area',
            field=models.FloatField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='ipheight',
            field=models.FloatField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='ipwidth',
            field=models.FloatField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='opheight',
            field=models.FloatField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='opwidth',
            field=models.FloatField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='quantity',
            field=models.IntegerField(default='1', max_length=100),
        ),
    ]
