# Generated by Django 4.1.1 on 2023-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0215_alter_tentativeglassfinalitem_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderglassitems',
            name='area',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
