# Generated by Django 4.1.1 on 2023-12-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0216_alter_purchaseorderglassitems_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentativeglassitem',
            old_name='window',
            new_name='width',
        ),
    ]
