# Generated by Django 4.1.1 on 2023-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0218_alter_glasscutting_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderglassitems',
            old_name='uchannels',
            new_name='uinsert',
        ),
        migrations.AddField(
            model_name='tentativeglassfinalitem',
            name='uinsert',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='glasscutting',
            name='revision',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
