# Generated by Django 4.1.1 on 2023-12-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0219_rename_uchannels_purchaseorderglassitems_uinsert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeglassbooking',
            name='uinsert',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='uinsert',
            field=models.IntegerField(default='1'),
        ),
    ]
