# Generated by Django 4.1.1 on 2023-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0220_tentativeglassbooking_uinsert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeglassbooking',
            name='uinsert',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='uinsert',
            field=models.IntegerField(default='0'),
        ),
    ]
