# Generated by Django 4.1.1 on 2023-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0221_alter_tentativeglassbooking_uinsert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeglassfinalitem',
            name='recieved',
            field=models.IntegerField(default='1'),
        ),
    ]
