# Generated by Django 4.1.1 on 2023-12-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0222_tentativeglassfinalitem_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeglassfinalitem',
            name='recieved',
            field=models.IntegerField(default='0'),
        ),
    ]
