# Generated by Django 4.1.1 on 2023-12-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0223_alter_tentativeglassfinalitem_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteFromSupplierGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('DNINFromsupplierNoGlass', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='DNINFromsupplierNoGlass', to='store.deliverynotefromsupplier')),
                ('SupplierglassType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SupplierglassType', to='store.tentativeglassfinalitem')),
                ('glassCuttingsupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassCuttingsupplier', to='store.glasscutting')),
            ],
        ),
    ]
