# Generated by Django 4.1.1 on 2024-01-18 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0227_cities_customers_salesmen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='1', max_length=100)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('remarks', models.CharField(max_length=200)),
                ('BudgetHead', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='BudgetHead', to='store.accountshead')),
                ('ProjectBudget', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ProjectBudget', to='store.project')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
