# Generated by Django 4.1.1 on 2024-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0228_projectbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeglass',
            name='revision',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
