# Generated by Django 4.1.1 on 2024-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0229_alter_tentativeglass_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbudget',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
