# Generated by Django 4.1.1 on 2024-01-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0231_projectbudget_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFromSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=100, null=True)),
                ('balance', models.CharField(default='0', max_length=100, null=True)),
                ('InvoiceRef', models.CharField(default='NA', max_length=200, null=True)),
                ('DNRef', models.CharField(default='NA', max_length=200, null=True)),
                ('is_review', models.CharField(default='0', max_length=100, null=True)),
                ('is_verify', models.CharField(default='0', max_length=100, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(null=True)),
                ('priority', models.CharField(default='1', max_length=100, null=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('InvoicePO', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoicePO', to='store.purchaseorder')),
                ('InvoiceProject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceProject', to='store.project')),
            ],
        ),
    ]
