# Generated by Django 4.1.1 on 2024-02-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0232_invoicefromsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemFromSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=100, null=True)),
                ('quantity', models.CharField(default='0', max_length=100, null=True)),
                ('is_review', models.CharField(default='0', max_length=100, null=True)),
                ('is_verify', models.CharField(default='0', max_length=100, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('InvoiceFromSupplierNO', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceFromSupplierNO', to='store.invoicefromsupplier')),
                ('InvoiceItemPO', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItemPO', to='store.purchaseorder')),
                ('InvoiceItemProject', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItemProject', to='store.project')),
            ],
        ),
    ]
