# Generated by Django 4.1.1 on 2024-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0233_invoiceitemfromsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefromsupplier',
            name='InvoiceSupplier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceSupplier', to='store.supplier'),
        ),
    ]
