# Generated by Django 4.1.1 on 2024-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0235_invoiceitemfromsupplier_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat',
            field=models.IntegerField(blank=True, default='5', null=True),
        ),
    ]
