# Generated by Django 4.1.1 on 2024-02-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0236_supplier_balance_supplier_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifiedpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CertificationID', models.CharField(default='0', max_length=100, null=True)),
                ('CertifiedAmount', models.CharField(default='0', max_length=100, null=True)),
                ('CertificationDate', models.DateField(max_length=100, null=True)),
                ('Remarks', models.CharField(default='0', max_length=100, null=True)),
                ('ApprovedAmount', models.CharField(default='0', max_length=100, null=True)),
                ('ApprovalDate', models.DateField(max_length=100, null=True)),
                ('is_verify', models.CharField(default='0', max_length=100, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=100, null=True)),
                ('CertifiedProject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertifiedProject', to='store.project')),
            ],
        ),
    ]
