# Generated by Django 4.1.1 on 2024-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0238_nonsystemitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsystemitems',
            name='powder_eta',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='powder_mto_taking',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='powder_order_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_approval_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_approval_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_desiginer',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_end_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_revision',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_start_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sd_submission_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sheet_eta',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sheet_fabrication_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sheet_mto_taking',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='sheet_order_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='steel_eta',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='steel_fabrication_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='steel_galvanizing_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='steel_mto_taking',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonsystemitems',
            name='steel_order_status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
