# Generated by Django 4.1.1 on 2024-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0239_nonsystemitems_powder_eta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsystemitems',
            name='sd_approval_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nonsystemitems',
            name='sd_desiginer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
