# Generated by Django 4.1.1 on 2024-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0240_alter_nonsystemitems_sd_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSystemDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(default='1', max_length=100, null=True)),
                ('refrence', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('qty', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('submitted_at', models.DateField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('approval_date', models.DateField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
