# Generated by Django 4.1.1 on 2024-02-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0241_nonsystemdamage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonsystemdamage',
            old_name='approval_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='nonsystemdamage',
            old_name='submitted_at',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='nonsystemdamage',
            old_name='approval_status',
            new_name='recieved_status',
        ),
        migrations.RenameField(
            model_name='nonsystemdamage',
            old_name='remarks',
            new_name='replacement_status',
        ),
    ]
