# Generated by Django 4.1.1 on 2024-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0243_alter_nonsystemdamage_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsystemdamage',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
