# Generated by Django 4.1.1 on 2024-02-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0244_alter_nonsystemdamage_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_approval_date',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_approval_status',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_desiginer',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_end_date',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_revision',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_start_date',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_status',
        ),
        migrations.RemoveField(
            model_name='nonsystemitems',
            name='sd_submission_status',
        ),
    ]
