# Generated by Django 4.1.1 on 2024-02-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0245_remove_nonsystemitems_sd_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSystemItemsSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sd_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sd_start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('sd_end_date', models.DateField(blank=True, max_length=100, null=True)),
                ('sd_submission_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sd_approval_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sd_revision', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sd_approval_date', models.DateField(blank=True, max_length=100, null=True)),
                ('sd_desiginer', models.CharField(blank=True, max_length=100, null=True)),
                ('stats', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
