# Generated by Django 4.1.1 on 2024-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0246_nonsystemitemssd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonsystemitemssd',
            old_name='stats',
            new_name='status',
        ),
        migrations.AddField(
            model_name='nonsystemitemssd',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
