# Generated by Django 4.1.1 on 2024-02-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0247_rename_stats_nonsystemitemssd_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrence', models.CharField(default='0', max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('Type', models.CharField(default='0', max_length=100, null=True)),
                ('Remarks', models.CharField(default='0', max_length=100, null=True)),
                ('Status', models.CharField(default='0', max_length=100, null=True)),
                ('NCRProject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NCRProject', to='store.project')),
            ],
        ),
    ]
