# Generated by Django 4.1.1 on 2024-02-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0248_ncr'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1', max_length=100)),
                ('description', models.CharField(default='1', max_length=100)),
                ('location', models.CharField(default='NA', max_length=100)),
                ('qty', models.CharField(default='NA', max_length=100)),
                ('balance', models.CharField(default='NA', max_length=100)),
                ('status', models.CharField(default='NA', max_length=100)),
                ('remarks', models.CharField(default='NA', max_length=100)),
                ('NCRId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='NCRId', to='store.ncr')),
                ('NCRItemProject', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NCRItemProject', to='store.project')),
            ],
        ),
    ]
