# Generated by Django 4.1.1 on 2024-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0249_ncritems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncritems',
            name='balance',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='ncritems',
            name='qty',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
