# Generated by Django 4.1.1 on 2024-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0250_alter_ncritems_balance_alter_ncritems_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncritems',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncr',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ncritems',
            name='balance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ncritems',
            name='qty',
            field=models.IntegerField(default='0'),
        ),
    ]
