# Generated by Django 4.1.1 on 2024-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0252_rename_al_eta_nonsystemitems_eta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsystemdamage',
            name='mainid',
            field=models.IntegerField(db_column='mainid', default='0'),
        ),
        migrations.AddField(
            model_name='nonsystemitemssd',
            name='mainid',
            field=models.IntegerField(db_column='mainid', default='0'),
        ),
    ]
