# Generated by Django 4.1.1 on 2024-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0253_nonsystemdamage_mainid_nonsystemitemssd_mainid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonsystemitems',
            name='mainid',
            field=models.IntegerField(db_column='mainid', default='0'),
        ),
    ]
