# Generated by Django 4.1.1 on 2024-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0255_project_phase_project_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSystemItemsMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ms_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ms_start_date', models.DateField(blank=True, max_length=100, null=True)),
                ('ms_end_date', models.DateField(blank=True, max_length=100, null=True)),
                ('ms_submission_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ms_approval_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ms_revision', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ms_approval_date', models.DateField(blank=True, max_length=100, null=True)),
                ('ms_desiginer', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('mainid', models.IntegerField(db_column='mainid', default='0')),
            ],
        ),
    ]
